---
title: "Metabarcoding_Weekly"
authors: "Evelyn Pain, Fatimah Bouderdaben, and Jimmy Erkens"
format: html
editor: visual
---

# Brief Github protocol (Jimmy)

JRE

-   Install Git

-   Import in project via version control

-   You will have a project and all the files on Github will be pulled locally

-   Generate a personal access token on Github

-   Make your changes

-   Commit your changes (and write what you did in the commit box)

-   Stage the files you want to push up (this is just checking a box)

    -   If you need to pull anything, pull it (you'll be prompted)

-   If there are any hiccups, follow the instructions in the R terminal (git merge --abort is your best friend!)

-   Push!

-   Make sure to pull before you get started in the future!

# Background and goals

ELP

Our internship team has 4 main goals:

1.  To gain familiarity with genomics/genetics literature and theory through the assigned readings

2.  To get practice with the lab skills necessary for extraction, PCR and sequencing (with the Oxford Nanopore MinION)

3.  To develop a working protocol to DNA metabarcode woolly fecal samples to detect insects (and plants?) in their diet

4.  To practice bioinformatics skills by identifying and comparing the species eaten by YTWMs and common woolly monkeys

ELP

# Extraction Protocol (**QIAGEN Stool Kit)**

This protocol is modified from the protocol developed by Mel Zarate in the SMAGL lab following modifications based on published protocols by Tony Di Fiore (University of Texas at Austin)

## General notes before starting

-   Ensure that you are wearing suitable PPE: a lab coat, protective eye glasses and gloves (you can consult the appropriate safety data sheets from product suppliers if you have any doubts)

-   Turn on the biosafety cabinet (BSC) and let it run for a minimum of 15 minutes before starting the protocol

-   Turn on the water bath and set it to 70 °C

-   Turn on the heat block and set it to 56 °C

-   Make up a new batch of 10% bleach solution (1 part bleach to 9 parts distilled water) for the day and dispose of any from previous days. Be sure to appropriately label the vessel with date and contents!

-   Aliquot sufficient 96-100% **ethanol** (available in the **Flammables Cabinet**) to a smaller vessel for use later in the protocol. Be sure to appropriately label the vessel with date and contents!

-   Clean all pipettes and work surfaces (including inside the biosafety cabinet) first with the bleach solution, then distilled water, and finally with 70% ethanol

-   Ensure that you have sufficient supplies (i.e., autoclaved, sterile tubes, pipette tips, etc.) before beginning

-   UV all tubes, pipettes and pipette tips in either the BSC or the PCR hood for 10 minutes before starting (be careful to limit your exposure to the UV light!)

-   Removed samples to be extracted from the freezer and let them thaw on ice

## Notes on the protocol

-   Make sure to label all tubes on both the top and sides (it is easy for labels to get rubbed off during the protocol)

-   Always include a control sample of sterile/DNAse free water for every extraction so that you can detect potential contamination!

-   Perform all centrifugation steps at room temperature (15--25 °C)

-   The 2 ml tubes used in step 4 should be wide enough to accommodate an InhibitEX Tablet. If it's not wide enough, you may need to break up the tablet to insert

## Required equipment and supplies

-   In this protocol, equipment/reagents available in the QIAGEN stool Kit will be marked in [blue]{style="color:blue"}. Equipment and supplies available in the SMAGL will be in [green]{style="color:green"}.
-   You will use the following pieces of equipment: a [biosafety cabinet]{style="color:green"}, [fridge]{style="color:green"} (located below the **PCR workstation**), [pipettes]{style="color:green"} (the extraction set are located inside the **BSC** or at the **extraction workstation**), [microcentrifuge]{style="color:green"} (you will need to use the largest centrifuge at the **Centrifuge Station** as this is the only one that goes this fast) set to 20,000 rcf (not rpm), a [benchtop microcentrifuge]{style="color:green"} (located at the **quantification workstation**), a [heating block]{style="color:green"} set to 56 °C, a [waterbath]{style="color:green"} set to 70 °C (located at the **extraction workstation**), a [vortexer]{style="color:green"} (located at the **extraction workstation** or inside **BSC**), a [tube rocker]{style="color:green"} (located at the **extraction workstation**), and a [bead-beater]{style="color:green"} (located in the **BSC**)
-   You will need [pipette tips]{style="color:green"} (located on shelves above the **PCR** or **quantification workstations**). ONLY use filter tips!
-   You will need [2 mL]{style="color:green"} and [1.5 mL tubes]{style="color:green"} which must be **autoclaved** prior to use! You'll have to count ahead in the protocol based on how many samples you're running and how many tubes you'll need to figure out the amount so that you'll be prepared
-   You will also need [96-100 % ethanol]{style="color:green"}

## Protocol

1.  Label the same number of [2ml tubes]{style="color:green"} as samples, plus one for a control

2.  Vortex the fecal sample for a few seconds

3.  Pipet 200 𝜇l of fecal slurry into the tube (you will need to cut the tips off each pipette tip with a razor blade to make the point wide enough to be able to suck up the sample)

4.  Add 1.6 ml of [Buffer ASL]{style="color:blue"} to each tube (if the solution has precipitated, dissolve by incubating at 70 °C in the [waterbath]{style="color:green"})

5.  Vortex each tube for 1 minute or until the sample is thoroughly homogenized (It is very important to vortex the samples thoroughly. This helps ensure maximum DNA concentration in the final eluate)

6.  Incubate samples at 56 ºC in the [heating block]{style="color:green"} for 30-60 min

7.  Incubate samples at room temperature in the tube rocker for 30 minutes

8.  An **optional** step is to further incubate the samples in the [heating block]{style="color:green"} at 23 ºC **overnight. THIS IS A POTENTIAL STOPPING POINT**

9.  Increase the temperature of the [heating block]{style="color:green"} to 70 ºC

10. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute to pellet stool particles (make sure that the centrifuge is **balanced**)

11. Label a new set of [2 ml tubes]{style="color:green"}

12. Pipet 1.4 ml of the supernatant into the new [2 ml tubes]{style="color:green"} and discard the pellet

13. Add 1 [InhibitEX Tablet]{style="color:blue"} or 500 𝜇l of [liquid InhibitEX]{style="color:blue"} (newer kits have liquid, older have tablets) to each sample

14. Vortex each sample immediately for 1 minute or until the [InhibitEX]{style="color:blue"} is completely suspended

15. Incubate suspension for 1 min at room temperature to allow inhibitors to adsorb to the [InhibitEX]{style="color:blue"} matrix

16. Label a new set of [2 ml tubes]{style="color:green"}

17. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 3 minutes to pellet stool particles and inhibitors bound to the [InhibitEX]{style="color:blue"} matrix (make sure that the centrifuge is **balanced**)

    -   **Note**: for difficult samples centrifugation for 3 minutes may result in a pellet that is not sufficiently compact. Therefore it may be difficult to remove enough supernatant to transfer 600 𝜇l supernatant after the next centrifugation step. In these cases, we recommend to centrifuge for 6 minutes
    -   **Note**: When processing more than 12 samples, for this step and step 17 we recommend processing batches of no more than 12 samples each. This is because the pellets formed after centrifugation will break up quickly if the supernatant is not removed immediately

18. Immediately after the [microcentrifuge]{style="color:green"} stops, pipet all of the supernatant into the clean [2 ml tubes]{style="color:green"} and discard the pellet (Transferring small quantities of pelleted material from the previous step will not affect the procedure)

19. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 3 minutes (make sure that the centrifuge is **balanced**)

20. Label a new set of [2 ml tubes]{style="color:green"}

21. Pipet 25 𝜇l of [proteinase K]{style="color:blue"} into the newly labeled tubes

22. Pipet 600 𝜇l supernatant from step 18 into the tubes containing the [proteinase K]{style="color:blue"}

23. Add 600 𝜇l [Buffer AL]{style="color:blue"}

    -   **Note**: do **NOT** add [proteinase K]{style="color:blue"} directly to [Buffer AL]{style="color:blue"}. It is essential that the sample and [Buffer AL]{style="color:blue"} are thoroughly mixed to form a homogeneous solution

24. Vortex tubes for 15 seconds

25. Incubate the tubes in the [heating block]{style="color:green"} at 70°C for 60 min

    -   You may want to briefly centrifuge the tubes using the small [benchtop centrifuge]{style="color:green"} at the **Quantification Station** to remove drops from the inside of the tube lid (make sure that the centrifuge is **balanced**)

26. Add 600 𝜇l of [96--100 % ethanol]{style="color:green"} to the lysate

27. Vortex briefly

    -   You may want to briefly centrifuge the tubes using the small [benchtop centrifuge]{style="color:green"} at the **Quantification Station** to remove drops from the inside of the tube lid (make sure that the centrifuge is **balanced**)

28. Label the lid of a new set of [QIAamp spin columns]{style="color:blue"} and [2 ml collection tubes]{style="color:blue"}

29. Carefully apply 600 𝜇l of the lysate to the [QIAamp spin columns]{style="color:blue"} without moistening the rim and close the cap

30. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

31. Carefully pull the [QIAamp spin columns]{style="color:blue"} out of the [collection tubes]{style="color:blue"} and discard the filtrate

    -   **Note**: if the lysate has not completely passed through the column after centrifugation, centrifuge again until the [QIAamp spin columns]{style="color:blue"} are empty

32. Replace the [QIAamp spin columns]{style="color:blue"} back into the now empty [collection tubes]{style="color:blue"}

33. Carefully open the [QIAamp spin column]{style="color:blue"}, apply a second aliquot of 600 𝜇l lysate and close the cap

34. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

35. Carefully pull the [QIAamp spin columns]{style="color:blue"} out of the [collection tubes]{style="color:blue"} and discard the filtrate

    -   **Note**: if the lysate has not completely passed through the column after centrifugation, centrifuge again until the [QIAamp spin column]{style="color:blue"} is empty

36. Replace the [QIAamp spin columns]{style="color:blue"} back into the now empty [collection tubes]{style="color:blue"}

37. Carefully open the [QIAamp spin column]{style="color:blue"}, apply a third aliquot of 600 𝜇l lysate and close the cap

38. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

39. Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

40. Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate

    -   **Note**: if the lysate has not completely passed through the column after centrifugation, centrifuge again until the [QIAamp spin column]{style="color:blue"} is empty

41. Carefully open the [QIAamp spin column]{style="color:blue"} and add 500 𝜇l of [Buffer AW1]{style="color:blue"} and close the cap

42. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

43. Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

44. Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate

45. Carefully open the [QIAamp spin column]{style="color:blue"} and add 500 𝜇l of [Buffer AW2]{style="color:blue"} and close the cap

46. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 3 minutes (make sure that the centrifuge is **balanced**)

    -   **Note**: residual [Buffer AW2]{style="color:blue"} in the eluate may cause problems in downstream applications. Some centrifuge rotors may vibrate upon deceleration, resulting in the flow-through, which contains [Buffer AW2]{style="color:blue"}, contacting the [QIAamp spin column]{style="color:blue"}. Removing the [QIAamp spin column]{style="color:blue"} and [collection tube]{style="color:blue"} from the rotor may also cause flow-through to come into contact with the [QIAamp spin column]{style="color:blue"}

47. Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

48. Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate

49. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   **Note**: this step is optional but recommended help eliminate the chance of [Buffer AW2]{style="color:blue"} carryover

50. Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

51. Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate (the filtrate should be minimal)

52. Place [Buffer AE]{style="color:blue"} in the waterbath at 70 ºC to incubate for 10 minutes

53. Label a new set of [2 ml tubes]{style="color:green"} (These are the tubes going into the freezer, so labeling is extra important!)

54. Transfer the [QIAamp spin columns]{style="color:blue"} into the new set of [2 ml tubes]{style="color:green"}

55. Carefully open the [QIAamp spin columns]{style="color:blue"}, pipet 100 𝜇l of [Buffer AE]{style="color:blue"} directly onto the QIAamp membrane (do not touch the membrane with the pipette tip), and close the cap

56. Incubate the tubes at room temperature for 25 minutes

57. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute to elute the DNA (you will need to use the largest centrifuge at the **Centrifuge Station** as this is the only one that goes this fast)

58. Pull the filter portion of the tube up and cap the tube (you can either discard it or save them if you want to try and get more DNA out of them)

59. The liquid in the tube contains the DNA from the samples and should be stored in the [-20 °C freezer]{style="color:green"} when not in use! (Be sure to record where in the freezer you've placed them, and make sure that they are all together in a single, clearly labeled container/rack)

60. The next step is to quantify the DNA in the samples (this is done by measuring the dsDNA concentration using the [Quantus]{style="color:green"} and the sample A260/A280 using the [Nanodrop]{style="color:green"}, both are located at the **Extraction Workstation**). The results should be recorded in your lab notebook

    -   **Note**: DNA yield is typically 15--60 𝜇g but, depending on the individual stool sample and the way it was stored, may range from 5 to 100 𝜇g. DNA concentration is typically 75--300 ng/𝜇l

# Quantus Quantitation Protocol

Manufacturer's protocol, without modifications from Melissa Zarate.

## Important Notes

-   Warm all assay components to room temperature before use.

-   You may need to prepare 1X TE buffer from more concentrated stock, although 1X TE Buffer is also available in the cabinets above the Centrifuge Workstation, and may already be pre-prepared in the Underbench Fridge.

-   If you have very little sample available, you may run this protocol using 1 μl rather than 2 μl.

-   Before running a tube in the Quantus, remember to wipe the tube down with Kimwipes to make sure the tube is clear.

## Required Equipment

-   QuantiFluor® dsDNA System (Cat.# E2670) \[**Underbench Fridge - PCR Workstation**\], elements available in this kit will be noted in **bold blue**, elements that are available in the lab will be noted in **bold black**.

-   QuantusTM Fluorometer (Cat.# E6150) \[**Quantitation Workstation**\]

-   Vortex 

-   Microcentrifuge 

-   Thin-walled 0.5ml PCR tubes (Cat.# E4941 or Axygen Cat.# PCR-05-C). Make sure enough are available prior to beginning! You may need to autoclave a new set - these are available above the autoclave \[**Autoclave Workstation**\].

-   Nuclease-free water \[Cabinet above water station\]

-   Pre-label your tubes to speed things up!

# Primer Selection

We will be using two sets of primers to identify insect species in the samples, and one set of primers to identify the plant species. All sets of primers have been successfully used by Dr. Mallott with various New World monkey species.

# Feb 12 - Feb 18

JRE

This was the week we were supposed to start the extraction protocol, but got postponed.

Fati: Practice Pipetting

# Feb 20 - Feb 25

<input type="checkbox" id="cbox3" value="third_checkbox"> <label for="cbox3"> Can I only select an ID? </label><br>

# Feb 26 - Mar 3

February 29, 2024:

ELP and JRE:

-   UV'd 1000𝜇l pipettes, 200𝜇l pipettes, 12 2ml lo-bind tubes, razor blades, 200 and 1000 𝜇l tips.
-   Set heatblock to 56C
-   ELP: made 10% bleach
-   ELP: made ice bath; put samples in ice bath
-   Wiped BSC down with 70% ethanol, water (twice), then 10% bleach

Testing the 1000ml pipettes (ELP) (notetaker = FAB and JRE)

-   They both look to be pipetting the same amount (marked with Sharpie)

1.  Pipet 200 𝜇l of fecal slurry into the microcentrifuge tube. You may need to cut the end of the pipet tip with a razor blade, if necessary, to make pipetting easier. Remember to vortex the sample prior to pipetting, to make sure you are getting a good mixture of buffer and feces.

-   Label tubes (completed by JRE at 5:13pm)
-   Adding 200 micro l water to control tube (completed by JRE at 5:16pm)
-   Vortex sample VOYT-18-017 and pipette 200 micro l into tube 03 (completed by ELP at 5:18pm)
-   Vortex sample VOYT-18-036 and pipette almost 200 micro l into tube 04 (completed by ELP at 5:19)
-   Vortex sample GIUNCHI-18-001 and pipette 200 micro l into tube 05 (completed by ELP at 5:20)
-   Vortex sample DIFIORE-18-025 and pipette 200 micro l into tube 06 (completed by ELP at 5:25)
-   Vortex sample DIFIORE-18-031 and pipette 200 micro l into tube 09 (completed by JRE at 5:28)
-   Vortex sample DIFIORE-18-032 and pipette 200 micro l into tube 11 (completed by JRE at 5:33)
-   Vortex sample VOYT-18-029 and pipette 200 micro l into tube 02 (completed by JRE at 5:35)
-   Vortex sample GOMEZ-18-190 and pipette 200 micro l into tube 01 (completed by FAB at 5:39)
-   Vortex sample VOYT-18-006 and pipette 200 micro l into tube 10 (completed by FAB at 5:44)
-   Vortex sample DIFIORE-18-026 and pipette 200 micro l into tube 07 (completed by FAB at 5:46)
-   Vortex sample DIFIORE-18-027 and pipette 200 micro l into tube 08 (completed by FAB at 5:48)

2.  Add 1.6 ml Buffer ASL to each stool sample. Vortex continuously for 1 min or until the stool sample is thoroughly homogenized. Note: It is very important to vortex the samples thoroughly. This helps ensure maximum DNA concentration in the final eluate.

-   Pipette 800 micro l of Buffer ASL to each tube twice, changing pipette tips each time (using 2 pipette tips per tube). (ELP completed control, tube 03, tube 04, and tube 05 at 5:53; JRE completed tube 06, 09, 11\[slightly less buffer was added\], and 02 at 6:03; FAB completed tube 01, 10, 07, and 08 at 6:08)

-   Vortex each of the tubes for 1 minute (2 at a time, 1 in each hand); double check that tubes are closed

-   Completed in shifts by ELP, JRE, and FAB at 6:17.

3.  Incubate samples at 56ºC in the Dry Bath for 30-60 min (60 minutes), then for an additional 30 min on Tube Rocker. Optional: further incubate in the Dry Bath at 23 degrees C overnight.

-   Started 56 degree C Dry Bath at 6:18 pm (completed at 7:22)
    -   ELP, FAB, and JRE cleaned the BSC with ethanol, water, then bleach
-   Started Tube Rocker at (completed at ), unknown, changes didn't get pushed or committed
    -   We got out of lab \~8PM JRE
-   Left in overnight 23 degrees C Dry Bath
    -   Dry Bath went down below 23 degrees C to 16.3 degrees C at 9:56 PM
    -   Dry Bath was reset to 23 degrees C by FAB and was at temp at 10:02 PM

March 1, 2024

-   Increase the temperature of the [heating block]{style="color:green"} to 70 ºC

    -   Removed tubes from Dry Bath at 9:23 AM and placed in rack in BSC (at 23 degrees C), set Dry Bath to 70 degrees C (JRE)

    -   ELP, FAB, and JRE mixed 10% bleach and wiped down BSC and microcentrifuge at 11:20 AM

    -   ELP, FAB, and JRE UV'd the pipettes for 10min

-   Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute to pellet stool particles (make sure that the centrifuge is **balanced**)

    -   ELP, FAB, and JRE started microcentrifuge at 20,000 rcf at 11:28 (took \~24s to reach speed) ended at 11:29

<!-- -->

-   Label a new set of [2 ml tubes]{style="color:green"}

    -   JRE labeled tubes at 11:27

-   Pipet 1.4 ml of the supernatant into the new [2 ml tubes]{style="color:green"} and discard the pellet

    -   ELP pipetted 700 micro l of supernatant 2 times (did not switch tips within tubes, 1 pipette tip was used per tube) into tubes 05, 03, 04, and 11. (completed at 11:37 am)

    -   JRE pipetted 700 micro l of supernatant 2 times into tubes 10 and 02. The pellet was disturbed in tube 01. Tube 01 and the control were re-centrifuged at 20,000 rcf for 1 min. JRE continued with tube 06 then re-pipetted 01. (completed at 11:47 am)

    -   FAB pipetted 700 micro l of supernatant 2 times into tubes 07, 09, 08, and CL. (completed at 11:52).

    -   Pellets were tossed at 11:53, JRE UV'd an extra set of 1000 micro pipette tips

-   Add 1 [InhibitEX Tablet]{style="color:blue"} or 500 𝜇l of [liquid InhibitEX]{style="color:blue"} (newer kits have liquid, older have tablets) to each sample

    -   ELP pipetted 500 micro l of liquid InhibitEX into tubes 05, 03, 04, and 11. A new pipette tip was used for each tube. (completed at 11:55)

    -   JRE pipetted 500 micro l of liquid InhibitEX into tubes 10, 02, 06, 01 using a new pipette tip per tube. (completed at 11:58)

    -   FAB pipetted 500 micro l of liquid InhibitEX into tubes 07, 09, 08, and CL using a new pipette tip per tube. (completed at 12:01).

-   Vortex each sample immediately for 1 minute or until the [InhibitEX]{style="color:blue"} is completely suspended

    -   JRE, ELP, and FAB switched off vortexing two tubes at a time (one in each hand) for 1 min. (completed at 12:08)

-   Incubate suspension for 1 min at room temperature to allow inhibitors to adsorb to the [InhibitEX]{style="color:blue"} matrix

    -   completed at 12:09.

-   Label a new set of [2 ml tubes]{style="color:green"}

    -   Completed by ELP at 12:04.

-   Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 3 minutes to pellet stool particles and inhibitors bound to the [InhibitEX]{style="color:blue"} matrix (make sure that the centrifuge is **balanced**)

    -   **Note**: for difficult samples centrifugation for 3 minutes may result in a pellet that is not sufficiently compact. Therefore it may be difficult to remove enough supernatant to transfer 600 𝜇l supernatant after the next centrifugation step. In these cases, we recommend to centrifuge for 6 minutes
    -   **Note**: When processing more than 12 samples, for this step and step 17 we recommend processing batches of no more than 12 samples each. This is because the pellets formed after centrifugation will break up quickly if the supernatant is not removed immediately
    -   ELP and JRE complete microcentrifuging the 12 tubes at 20,000 rcf for 6 min at 12:19.

-   Immediately after the [microcentrifuge]{style="color:green"} stops, pipet all of the supernatant into the clean [2 ml tubes]{style="color:green"} and discard the pellet (Transferring small quantities of pelleted material from the previous step will not affect the procedure)

    -   Pipette was set to 900 micro l.

    -   ELP pipetted 900 micro l of supernatant twice (switching pipette tips between tubes) into tubes 03, 04, 05, and 11. Completed at 12:25.

    -   JRE pipetted 900 micro l of supernatant twice (switching pipette tips between tubes) into tubes 10, 02, 06, 01. Completed at 12:30.

    -   FAB pipetted 900 micro l of supernatant twice (switching pipette tips between tubes) into tubes 07, 08, 09, and CL. Completed at 12:37

-   Label a new set of [2 ml tubes]{style="color:green"}

    -   completed by ELP at 12:16.

-   Pipet 25 𝜇l of [proteinase K]{style="color:blue"} into the newly labeled tubes

    -   JRE UV'd a box of 10 micro pipette tips for 10 min. Completed at 12:27. (this was necessary)

    -   ELP pipetted 25 micro l of proteinase K (switching pipette tips between tubes) into the newly labeled empty 2 ml tubes 03, 04, 05, and 11. Completed at 12:40.

    -   JRE pipetted 25 micro l of proteinase K (switching pipette tips between tubes) into the newly labeled empty 2ml tubes 10, 02, 06, 01. Completed at 12:43

    -   FAB pipetted 25 micro l of proteinase K (switching pipette tips between tubes) into the newly labeled and empty 2 ml tubes 07, 08, 09, and CL. Completed at 12:46.

-   Pipet 600 𝜇l supernatant from step 18 into the tubes containing the [proteinase K]{style="color:blue"}

    -   ELP pipetted 600 micro l of supernatant into the new proteinase K tubes labeled 03, 04, 05, and 11. Completed at 12:49.

    -   JRE pipetted 600 micro l of supernatant into the new proteinase K tubes labeled 10, 02, 06, 01. Completed at 12:52.

    -   FAB pipetted 600 micro l of supernatant into the new proteinase K tubes labeled 07, 08, 09, and CL. Completed at 12:55).

    -   A pink post-it note was added to the tray with the leftover supernatant tubes and set to the side to distinguish between those and our active sample tubes in a separate tray.

-   Add 600 𝜇l [Buffer AL]{style="color:blue"}

    -   **Note**: do **NOT** add [proteinase K]{style="color:blue"} directly to [Buffer AL]{style="color:blue"}. It is essential that the sample and [Buffer AL]{style="color:blue"} are thoroughly mixed to form a homogeneous solution
    -   ELP pipetted 600 micro l of Buffer AL (switching pipette tips between tubes) into the active sample tubes 03, 04, 05, and 11. Completed at 12:58.
    -   JRE pipetted 600 micro l of Buffer AL (switching pipette tips between tubes) into the active sample tubes 10, 02, 06, and 01. (Had to switch to using Buffer AL from the QIAmp DNA Blood Kit for tubes 10 and 02) Completed at 1:02.
    -   FAB pipetted 60 micro l of Buffer AL (from Blood Kit) into the active sample tubes 07, 08, 09, and CL. Completed at 1:06.

-   Vortex tubes for 15 seconds

    -   ELP Vortexed all 12 tubes for 15 sec (2 at a time). Completed at 1:08.

-   Incubate the tubes in the [heating block]{style="color:green"} at 70°C for 60 min

    -   You may want to briefly centrifuge the tubes using the small [benchtop centrifuge]{style="color:green"} at the **Quantification Station** to remove drops from the inside of the tube lid (make sure that the centrifuge is **balanced**)
    -   JRE started 60 min incubation at 1:10pm.
    -   Leftover supernatant tray was placed in the -20 fridge by ELP at 1:11.
    -   ELP took all 12 lysates out of Heat Block at 2:11.
    -   ELP benchtop centrifuged all 12 lysates for 5 seconds.

-   Add 600 𝜇l of [96--100 % ethanol]{style="color:green"} to the lysate

    -   FAB had an exam, not present for this part of protocol.

    -   ELP aliquotted 7.2mL of 96-100% ethanol into 2 LoBind Tubes (refilled in-between ELP and JRE pipetting ethanol). Completed at 2:17.

    -   ELP pipetted 600 micro l of 96-100% ethanol (switching pipette tips between tubes) to lysates 03, 04, 05, 11, 07, 09. Completed at 2:16.

    -   JRE pipetted 600 micro l of 96-100% ethanol (switching pipette tips between tubes) to lysates CL, 08, 02, 06, 01, and 10. Completed at 2:21.

-   Vortex briefly

    -   You may want to briefly centrifuge the tubes using the small [benchtop centrifuge]{style="color:green"} at the **Quantification Station** to remove drops from the inside of the tube lid (make sure that the centrifuge is **balanced**)
    -   ELP vortexed all 12 tubes for 15 sec (2 at a time). Centrifuged 6 tubes at a time for \~5s. Completed at 2:28.

-   Label the lid of a new set of [QIAamp spin columns]{style="color:blue"} and [2 ml collection tubes]{style="color:blue"}

    -   Completed by JRE at 2:29

-   Carefully apply 600 𝜇l of the lysate to the [QIAamp spin columns]{style="color:blue"} without moistening the rim and close the cap

    -   ELP pipetted 600 micro l of lysate (switching pipette tips between tubes) to QIAamp spin columns CL, 01, 02, 03, 04, 05. Completed at 2:33.

    -   JRE pipetted 600 micro l of lysate (switching pipette tips between tubes) to QIAamp spin columns 06, 07. 08, 09, 10, 11. Completed at 2:38.

-   Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   Completed by ELP at 2:41 (lid was not on, made a scary noise).

-   Carefully pull the [QIAamp spin columns]{style="color:blue"} out of the [collection tubes]{style="color:blue"} and discard the filtrate

    -   **Note**: if the lysate has not completely passed through the column after centrifugation, centrifuge again until the [QIAamp spin columns]{style="color:blue"} are empty
    -   Sample 10 and 08 did not completely filter out. Some of Sample 10 spilled out onto centrifuge (wiped with kimwipe and Bleach). ELP redid and completed centrifuge step for these samples at 2:47

-   Replace the [QIAamp spin columns]{style="color:blue"} back into the now empty [collection tubes]{style="color:blue"}

-   Carefully open the [QIAamp spin column]{style="color:blue"}, apply a second aliquot of 600 𝜇l lysate and close the cap

    -   ELP emptied collection tubes CL, 01, 02, 03, 04, 05 and pipetted 600 micro l of lysate (switching pipette tips between tubes) to QIAamp spin columns. Completed at 2:53.

    -   JRE emptied collection tubes 06, 07, 08, 09, 10, 11 and pipetted 600 micro l of lysate (switching pipette tips between tubes) to QIAamp spin columns. Completed at 2:58.

-   Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   Completed by JRE at 3:01

-   Carefully pull the [QIAamp spin columns]{style="color:blue"} out of the [collection tubes]{style="color:blue"} and discard the filtrate

    -   **Note**: if the lysate has not completely passed through the column after centrifugation, centrifuge again until the [QIAamp spin column]{style="color:blue"} is empty

-   Replace the [QIAamp spin columns]{style="color:blue"} back into the now empty [collection tubes]{style="color:blue"}

-   Carefully open the [QIAamp spin column]{style="color:blue"}, apply a third aliquot of 600 𝜇l lysate and close the cap

    -   ELP emptied collection tubes CL, 01, 02, 03, 04, 05 (wiping the rim of each tube with 1 kimwipe) and pipetted final 600 micro l of lysate (switching pipette tips between tubes) to QIAamp spin columns. Discarded old tubes Completed at 3:10

    -   JRE emptied collection tubes 06, 07, 08, 09, 10, 11 (wiping the rim of each tube with 1 kimwipe) and pipetted final 600 micro l of lysate (switching pipette tips between tubes) to QIAamp spin columns. Discard old tubes Completed at 3:15

    -   Note, final micro l of lysate for all tubes not quite 600 micro l.

-   Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   Completed by ELP at 3:16.

    -   Sample 07 had to be respun. Completed by ELP and JRE at 3:20

-   Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

-   Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate

    -   **Note**: if the lysate has not completely passed through the column after centrifugation, centrifuge again until the [QIAamp spin column]{style="color:blue"} is empty

-   Carefully open the [QIAamp spin column]{style="color:blue"} and add 500 𝜇l of [Buffer AW1]{style="color:blue"} and close the cap

    -   JRE disposed and replaced each collection tube, then pipetted 500 micro l of Buffer AW1 to spin columns 06, 07, 08, 09, 10, 11. Completed at 3:25.

    -   ELP disposed and replaced each collection tube, then pipetted 500 micro l of Buffer AW1 to spin columns CL, 01, 02, 03, 04, 05. Completed at 3:29.

-   Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

-   Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

-   Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate

-   Carefully open the [QIAamp spin column]{style="color:blue"} and add 500 𝜇l of [Buffer AW2]{style="color:blue"} and close the cap

-   Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 3 minutes (make sure that the centrifuge is **balanced**)

    -   ELP started at 4:41

        -   **Note**: residual [Buffer AW2]{style="color:blue"} in the eluate may cause problems in downstream applications. Some centrifuge rotors may vibrate upon deceleration, resulting in the flow-through, which contains [Buffer AW2]{style="color:blue"}, contacting the [QIAamp spin column]{style="color:blue"}. Removing the [QIAamp spin column]{style="color:blue"} and [collection tube]{style="color:blue"} from the rotor may also cause flow-through to come into contact with the [QIAamp spin column]{style="color:blue"}

-   Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

-   Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate

-   Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   **Note**: this step is optional but recommended help eliminate the chance of [Buffer AW2]{style="color:blue"} carryover
        -   ELP started at 3:52

-   Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

-   Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate (the filtrate should be minimal)

-   Place [Buffer AE]{style="color:blue"} in the waterbath at 70 ºC to incubate for 10 minutes

    -   ELP started at 3:33

-   Label a new set of [2 ml tubes]{style="color:green"} (These are the tubes going into the freezer, so labeling is extra important!)

-   Transfer the [QIAamp spin columns]{style="color:blue"} into the new set of [2 ml tubes]{style="color:green"}

-   Carefully open the [QIAamp spin columns]{style="color:blue"}, pipet 100 𝜇l of [Buffer AE]{style="color:blue"} directly onto the QIAamp membrane (do not touch the membrane with the pipette tip), and close the cap

    -   ELP started at 4:12.

-   Incubate the tubes at room temperature for 25 minutes

    -   ELP started at 4:15

-   Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute to elute the DNA (you will need to use the largest centrifuge at the **Centrifuge Station** as this is the only one that goes this fast)

    -   ELP and JRE completed at 4:48.

<!-- -->

-   Pull the filter portion of the tube up and cap the tube (you can either discard it or save them if you want to try and get more DNA out of them)

    -   ELP completed at 4:56.

-   The liquid in the tube contains the DNA from the samples and should be stored in the [-20 °C freezer]{style="color:green"} when not in use! (Be sure to record where in the freezer you've placed them, and make sure that they are all together in a single, clearly labeled container/rack)

-   The next step is to quantify the DNA in the samples (this is done by measuring the dsDNA concentration using the [Quantus]{style="color:green"} and the sample A260/A280 using the [Nanodrop]{style="color:green"}, both are located at the **Extraction Workstation**). The results should be recorded in your lab notebook

    -   JRE labeled 0.5ml tubes and began UV'ing 10micro and 200 micro l pipette tips and pipettes at 4:50.

        1\. If necessary, prepare **1X TE Buffer**: to do this, you may need to dilute **20X TE Buffer** 20-fold with **nuclease-free water**. We do also have 1X TE BUffer available in the cabinet above the Centrifuge Workstation; there may also be pre-prepared 1X TE Buffer in the Underbench Fridge.

    -   Done prior to starting.

        -   2\. Prepare Working Solution: Dilute the **QuantiFluor® dsDNA Dye** 1:400 in **1X TE buffer**, and mix. Working Solution may be available in the Underbench Fridge.

            -   Done prior to starting.

            -   Ran out of Working solution at 11th tube, ELP and JRE made \~1ml (3 parts dye to 1,197 TEx1) Working solution following protocol at 5:34.

                3\. Prepare Blank sample: Mix 2 μl of **1X TE buffer** with 200 μl of **QuantiFluor® dsDNA Dye** Working Solution in an empty **0.5 ml PCR tube**. **Vortex** well and protect tube from light (we do this by covering the tube with aluminum foil).

            -   JRE pipetted 2 micro l of 1X TE buffer into 0.5ml tube at 5:10

            -   ELP pipetted 200 micro l of Working solution at 5:24.

                4\. Prepare Standard: Add 2 μl of the provided **DNA Standard** (100 ng/μl) to 200 μl of **QuantiFluor® dsDNA Dye** working solution in an empty **0.5 ml PCR tube**. **Vortex** well and protect tube from light.

            -   JRE pipetted 2 microl l of DNA Standard into 0.5 tube at 5:11

            -   ELP pipetted 200 micro l of Working solution at 5:25.

                5\. Prepare Samples to be quantified: Add 1 or 2 μl of unknown samples to 200 μl of **QuantiFluor® dsDNA Dye** working solution in **0.5 ml PCR tubes**. **Vortex** well, and protect tube from light. You will want to pipet the sample up and down multiple times to make sure the sample is well-blended.

            -   JRE pipetted 2 micro l from samples CL, 01, 02, 03, 04. Completed at 5:16.

            -   ELP pipetted 200 micro l of Working solution to samples CL, 01, 02, 03, 04, 05. Completed at 5:28.

            -   ELP pipetted 2 micro l from samples 05, 06, 07, 08, 09, 10, 11. Completed at 5:22.

            -   JRE pipetted 200 micro l of Working solution to samples 06, 07, 08, 09, 10, 11

            -   Completed (after remaking \~1ml Working solution) at 5:44.

                6\. Incubate the prepared samples at room temperature for 5 minutes, protected from light.

            -   Finished incubating at 5:49.

                7\. Select the dsDNA protocol on the **Quantus Fluorometer**.

            -   Completed by ELP at 5:45.

                8\. Prior to running samples on the Quantus Fluorometer, you should blend them well by **vortexing** briefly and then spinning them down briefly using the **microcentrifuge**. You should also wipe down the sides of the tubes with **kimwipes** to make sure the sides are clear from smudges. 

            -   ELP vortexed and centrifuged each sample.

                9\. If needed (you will need it!), calibrate the **Quantus Fluorometer** by reading the blank (Step 3; this should read as 0 ng/μl) and standard (Step 4; this should read as 100 ng/μl) samples in the Calibration screen, then select "Save". 

                -   **Note**: a few ng/μl away from what it should be is ok... but large deviations need to be troubleshooted!

            -   Calibration complete at 5:54.

                10\. Enter the volume of the unknown sample (1--2 μl used in Step 5) and desired concentration units (in our case, ng/μl).

            -   Already set prior to starting

                11\. Pipette to mix each sample at least 10 times before putting the desired amount in the working solution. 

            -   Done

                12\. One sample at a time, mix by vortexing, briefly spin down and wipe the outside of the tube with a kimwipe. Measure fluorescence of the unknown sample and record the final sample concentration results.

            <!-- -->

            -   **Note**: DNA yield is typically 15--60 𝜇g but, depending on the individual stool sample and the way it was stored, may range from 5 to 100 𝜇g. DNA concentration is typically 75--300 ng/𝜇l
                -   Blank concentration: 0
                -   Standard concentration: 101

+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| Sample ID               | Taxon                | Label      | Final Concentration (ng/𝜇l) | **A260/A280 value** | Notes                                                  |
+=========================+======================+============+=============================+=====================+========================================================+
| Control (sterile water) | NA                   | AGI24-DBCL | 0.0258 -Q 8-N               | 5.7                 |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| GOMEZ-18-190            | Lagothrix lagotricha | AGI24-DB01 | 1.46 - Q 8.6-N              | 5.66                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-029             | Lagothrix lagotricha | AGI24-DB02 | 0.234 - Q 9.8-N             | 4.31                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-017             | Lagothrix lagotricha | AGI24-DB03 | 0.395 - Q 7.1 -N            | 8.38                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-036             | Lagothrix lagotricha | AGI24-DB04 | 0.195- Q 8.3-N              | 5.92                | Maybe not the entire 200𝜇l                             |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| GIUNCHI-18-001          | Lagothrix lagotricha | AGI24-DB05 | 0.595 - Q 10.2-N            | 3.97                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-025          | Lagothrix lagotricha | AGI24-DB06 | 0.202 - Q 10.3-N            | 4.15                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-026          | Lagothrix lagotricha | AGI24-DB07 | 1.09 - Q 11.2-N             | 4.22                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-027          | Lagothrix lagotricha | AGI24-DB08 | 0.145 - Q 8.5-N             | 4.17                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-031          | Lagothrix lagotricha | AGI24-DB09 | 0.151-Q 8.4-N               | 6.94                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-006             | Lagothrix lagotricha | AGI24-DB10 | 1.82-Q 15.4-N               | 3.03                | Pipetted most of 200 then a tiny bit extra some chunks |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-032          | Lagothrix lagotricha | AGI24-DB11 | 0.315-Q 14.13-N             | 6.9                 | Slightly less buffer was added                         |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+

JRE and ELP finished (sad) at 6:00.

# Mar 4 - Mar 10

March, 4, 2024

Written prior to there being a protocol on the website.

-   JRE selected nucleic acids option on the

1.  Clean pedestal w kimwipes and nuclease free water
2.  Blank w 2 micro l of nuclease free water or storage medium (Buffer ATE)
    -   JRE blanked with nuclease free water, not Buffer ATE.
3.  Between each sample, clean w kim wipe and nuclease free water
4.  2 micro l of sample for each run

JRE, FAB, and ELP finished at 12:12

## March 7, 2024

Second batch of extractions!

3:59, JRE and FAB created 10% bleach, finished cleaning biosafety cabinet, and UV'd pipettes and tips for 15 minutes.

-   FAB warmed up frozen supernatant with her hands started at 4:07 and completed at 4:12.

-   FAB vortexed each sample for 10 seconds. completed at 4:23

-   \*Continuing protocol from step 8 onwards

1.  Label a new set of [2 ml tubes]{style="color:green"}

    -   JRE completed at 4:22

2.  Pipet 25 𝜇l of [proteinase K]{style="color:blue"} into the newly labeled tubes

    -   JRE completed pipetting 25 micro l of proteinase k into new tubes CL, 01, 02, 03, 04, 05 at 4:30

    -   FAB completed pipetting 25 micro l of proteinase k into new tubes 06, 07, 08, 09, 10, 11 at 4:33

3.  Pipet 600 𝜇l leftover supernatant from step 18 into the tubes containing the [proteinase K]{style="color:blue"}

    -   FAB completed pipetting 600 micro l of supernatant into new tubes 06, 07, 08, 09, 10, 11 at 4:39

        -   ELP and FAB vortexed samples for 1 minute, started 4:40, completed 4:44.

        JRE completed pipetting 600 micro l of supernatant into new tubes CL, 01, 02, 03, 04, 05 at. Sample 5 spilled a bit, had to restart, (might be slightly under since it was the final bit of supernatant) added proteinase k to supernatant leftover/old tube. Completed at at 4:48.

        -   ELP and JRE vortexed samples for 1 minute starting at 4:49, completed at 5:52.

        -   The QIAamp Fast DNA Stool Mini Kit is expired, by well over 12 months. The DNAeasy PowerLyzer PowerSoil Kit is not expired.

4.  Add 600 𝜇l [Buffer AL]{style="color:blue"}

    -   **Note**: do **NOT** add [proteinase K]{style="color:blue"} directly to [Buffer AL]{style="color:blue"}. It is essential that the sample and [Buffer AL]{style="color:blue"} are thoroughly mixed to form a homogeneous solution
    -   JRE added 600 micro l of buffer AL to tubes CL, 01,02,03. Completed at 4:59.
    -   ELP added 600 micro l of buffer AL to tubes 04,05,06,07. Completed at 5:01.
    -   (ran low on buffer AL, switched to different DNeasy blood and tissue kit Buffer AL) FAB added 600 micro l of buffer AL to tubes 08,09,10,11. Completed at 5:04.

5.  Vortex tubes for 15 seconds (We are trying 1 minute instead)

    -   JRE vortexed all samples for 1 min. Completed at 5:13.

6.  Incubate the tubes in the [heating block]{style="color:green"} at 70°C for 60 min

    You may want to briefly centrifuge the tubes using the small [benchtop centrifuge]{style="color:green"} at the **Quantification Station** to remove drops from the inside of the tube lid (make sure that the centrifuge is **balanced**)

    -   Started incubation at 5:14. Completed at 6:14.

7.  Add 600 𝜇l of [96--100 % ethanol]{style="color:green"} to the lysate

    -   ELP completed benchtop centrifuging all samples at 6:18.

    -   JRE added 600 micro l of 100% ethanol to tubes CL, 01, 02, 03. Completed at 6:21.

    -   ELP added 600 micro l of 100% ethanol to tubes 04, 05, 06, 07. Completed at 6:22

    -   FAB added 600 micro l of 100% ethanol to tubes 08, 09, 10, 11. Completed at 6:25

8.  Vortex briefly

    -   ELP vortexed all samples for 1 min, completed at 6:31
    -   JRE benchtop centrifuged all samples. Completed at 6:34
    -   You may want to briefly centrifuge the tubes using the small [benchtop centrifuge]{style="color:green"} at the **Quantification Station** to remove drops from the inside of the tube lid (make sure that the centrifuge is **balanced**)

9.  Label the lid of a new set of [QIAamp spin columns]{style="color:blue"} and [2 ml collection tubes]{style="color:blue"}

    -   JRE labeled all spin columns and 2ml tubes, completed at 6:26.

    -   Note: Perhaps the protocol didn't work as well the first time because the samples weren't agitated enough? Per the QIAamp protocol we could have heated the suspended samples at 70C-95C for pathogen analysis (plant cell walls are tougher to break).

10. Carefully apply 600 𝜇l of the lysate to the [QIAamp spin columns]{style="color:blue"} without moistening the rim and close the cap

    -   JRE applied 600 micro l of lysate from samples CL, 01, 02, 03 to their labeled tubes. Completed at 6:37.

    -   ELP applied 600 micro l of lysate from samples 04, 05, 06, 07 to their labeled tubes. Completed at 6:40

    -   FAB applied 600 micro l of lysate from samples 08, 09, 10, 11 to their labeled tubes. Completed at 6:44

        -   FAB spilled a slight amount of sample 08 lysate at 6:41, cleaned with bleach and kimwipes.

11. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   ELP completed at 6:48.

12. Carefully pull the [QIAamp spin columns]{style="color:blue"} out of the [collection tubes]{style="color:blue"} and discard the filtrate

    -   JRE discarded filtrate and kimwiped all tubes. Completed at 6:55.
    -   **Note**: if the lysate has not completely passed through the column after centrifugation, centrifuge again until the [QIAamp spin columns]{style="color:blue"} are empty

13. Replace the [QIAamp spin columns]{style="color:blue"} back into the now empty [collection tubes]{style="color:blue"}

    -   Completed by JRE in previous step at 6:55.

14. Carefully open the [QIAamp spin column]{style="color:blue"}, apply a second aliquot of 600 𝜇l lysate and close the cap

    -   JRE added 600 micro l of lysate to tubes CL, 01, 02, 03. Completed at 6:57.

    -   ELP added 600 micro l of lysate to tubes 04, 05, 06, 07. Completed at 7:00.

    -   FAB added 600 micro l of lysate to tubes 08, 09, 10, 11. Completed at 7:03

        -   Pipetted up bubbles for lysate sample 10 (tiny bit of lysate likely got left behind)

15. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   Completed by ELP and FAB at 7:07

16. Carefully pull the [QIAamp spin columns]{style="color:blue"} out of the [collection tubes]{style="color:blue"} and discard the filtrate

    -   **Note**: if the lysate has not completely passed through the column after centrifugation, centrifuge again until the [QIAamp spin column]{style="color:blue"} is empty
    -   FAB discarded filtrate and kimwiped all tubes. Completed at 7:13.

17. Replace the [QIAamp spin columns]{style="color:blue"} back into the now empty [collection tubes]{style="color:blue"}

    -   Completed by FAB in previous step at 7:13.

18. Carefully open the [QIAamp spin column]{style="color:blue"}, apply a third aliquot of 600 𝜇l lysate and close the cap

    -   FAB added final 600 micro l of lysate to tubes 08, 09, 10, 11. Completed at 7:17.

    -   ELP added final 600 micro l of lysate to tubes 04, 05, 06, 07. Completed at 7:19.

    -   JRE added final 600 micro l of lysate to tubes CL, 01, 02, 03. Completed at 7:23

19. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   ELP completed micro centrifuging at 7:25.

20. Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

    -   (used lid-less 2ml tubes, did not label)

21. Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate

    -   Completed by ELP at 7:29.

        -   **Note**: if the lysate has not completely passed through the column after centrifugation, centrifuge again until the [QIAamp spin column]{style="color:blue"} is empty

22. Carefully open the [QIAamp spin column]{style="color:blue"} and add 500 𝜇l of [Buffer AW1]{style="color:blue"} and close the cap

    -   JRE added 500 micro l of Buffer AW1 to tubes CL, 01, 02, 03. Completed at 7:33.

    -   ELP added 500 micro l of Buffer AW1 to tubes 04, 05, 06, 07. Completed at 7:35.

    -   FAB added 500 micro l of Buffer AW1 to tubes 08, 09,10, 11. Completed at 7:38

23. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   JRE microcentrifuged tubes for 1 minute. Completed at 7:42. Tubes 9 and 11 did not finish filtering, centrifuged for an additional minute. Completed at 7:45.

24. Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

    -   (used lid-less 2ml tubes, did not label)

25. Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate

    -   Completed by ELP at 7:46.

26. Carefully open the [QIAamp spin column]{style="color:blue"} and add 500 𝜇l of [Buffer AW2]{style="color:blue"} and close the cap

    -   JRE added 500 micro l of Buffer AW2 to tubes CL, 01, 02, 03. Completed at 7:49.

    -   ELP added 500 micro l of Buffer AW2 to tubes 04, 05, 06, 07. Completed at 7:53.

        -   Pipette came apart, JRE UV'd a new 1000 micro l pipette for 10 min. Completed at

    -   FAB added 500 micro l of Buffer AW2 to tubes 08, 09, 10, 11. Completed at 7:55

27. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 3 minutes (make sure that the centrifuge is **balanced**)

    -   **Note**: residual [Buffer AW2]{style="color:blue"} in the eluate may cause problems in downstream applications. Some centrifuge rotors may vibrate upon deceleration, resulting in the flow-through, which contains [Buffer AW2]{style="color:blue"}, contacting the [QIAamp spin column]{style="color:blue"}. Removing the [QIAamp spin column]{style="color:blue"} and [collection tube]{style="color:blue"} from the rotor may also cause flow-through to come into contact with the [QIAamp spin column]{style="color:blue"}
    -   Completed by FAB and ELP at 8:02.

28. Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

    -   Completed by JRE at 7:58

29. Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate

    -   Completed by ELP and JRE at 8:04.

30. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute (make sure that the centrifuge is **balanced**)

    -   **Note**: this step is optional but recommended help eliminate the chance of [Buffer AW2]{style="color:blue"} carryover
    -   Completed by ELP at 8:07

31. Label the lid of a new set of [2 ml collection tubes]{style="color:blue"}

    -   (used lid-less tubes, did not label)

32. Place the [QIAamp spin columns]{style="color:blue"} into the new set of labeled [2 ml collection tubes]{style="color:blue"} and discard the tubes containing the filtrate (the filtrate should be minimal)

    -   Completed by ELP at 8:09.

33. Place [Buffer AE]{style="color:blue"} in the waterbath at 70 ºC to incubate for 10 minutes

    -   JRE put in waterbath at 7:56, kept in bath until 8:14.

34. Label a new set of [2 ml tubes]{style="color:green"} (These are the tubes going into the freezer, so labeling is extra important!)

    -   (used 1.5 ml tubes) JRE labeled at 8:10.

35. Transfer the [QIAamp spin columns]{style="color:blue"} into the new set of [2 ml tubes]{style="color:green"}

    -   Completed by ELP at 8:13

36. Carefully open the [QIAamp spin columns]{style="color:blue"}, pipet 100 𝜇l of [Buffer AE]{style="color:blue"} directly onto the QIAamp membrane (do not touch the membrane with the pipette tip), and close the cap

    -   NOTE: Online protocol calls for Buffer AE, kit came only with Buffer ATE (and kit protocol uses ATE at this step)

    <!-- -->

    -   JRE added 100 micro l of Buffer ATE to tubes CL, 01, 02, 03. Completed at 8:17.

    -   ELP added 100 micro l of Buffer ATE to tubes 04, 05, 06, 07. Completed at 8:19.

    -   FAB added 100 micro l of Buffer ATE to tubes 08, 09, 10,11. Completed at 8:22.

37. Incubate the tubes at room temperature for 25 minutes

    -   Incubated in dry bath at 20 c. Started at 8:22. Completed at 8:47

    -   FAB used the restroom (not in the lab)

38. Centrifuge the tubes in the [microcentrifuge]{style="color:green"} at 20,000 rcf (not rpm) for 1 minute to elute the DNA (you will need to use the largest centrifuge at the **Centrifuge Station** as this is the only one that goes this fast)

    -   ELP placed tubes (spin column "loosely" in 1.5ml tube) in the centrifuge in pairs with the lids facing outward.

    -   Completed centrifuging at 8:55.

39. Pull the filter portion of the tube up and cap the tube (you can either discard it or save them if you want to try and get more DNA out of them)

    -   JRE labeled tubes to save spin columns "Spin Column 2" at 8:28

    -   ELP removed spin columns from 1.5 ml tubes and put them in lid-less 2 ml tubes. Completed at 8:58.

40. The liquid in the tube contains the DNA from the samples and should be stored in the [-20 °C freezer]{style="color:green"} when not in use! (Be sure to record where in the freezer you've placed them, and make sure that they are all together in a single, clearly labeled container/rack)

    -   ELP and JRE placed spin columns and 1.5 ml tubes in freezer at 9:01.

41. The next step is to quantify the DNA in the samples (this is done by measuring the dsDNA concentration using the [Quantus]{style="color:green"} and the sample A260/A280 using the [Nanodrop]{style="color:green"}, both are located at the **Extraction Workstation**). The results should be recorded in your lab notebook

    -   **Note**: DNA yield is typically 15--60 𝜇g but, depending on the individual stool sample and the way it was stored, may range from 5 to 100 𝜇g. DNA concentration is typically 75--300 ng/𝜇l

-   ELP cleaned the BSC with ethanol, water, and bleach at 8:30.

## March 8, 2024

-   1\. If necessary, prepare **1X TE Buffer**: to do this, you may need to dilute **20X TE Buffer** 20-fold with **nuclease-free water**. We do also have 1X TE BUffer available in the cabinet above the Centrifuge Workstation; there may also be pre-prepared 1X TE Buffer in the Underbench Fridge.

-   JRE made and aliquotted 1X TE Buffer at 12:14.

    -   2\. Prepare Working Solution: Dilute the **QuantiFluor® dsDNA Dye** 1:400 in **1X TE buffer**, and mix. Working Solution may be available in the Underbench Fridge.

        -   ELP and JRE made 3.6 ml (3 parts dye to 1,197 TEx1 three times) Working solution following protocol at 12:23.

        -   JRE vortexed working solution at 12:31.

        -   JRE added 200 micro l of working solution into 14 autoclaved 0.5 ml tubes. Completed at 12:36.

            3\. Prepare Blank sample: Mix 2 μl of **1X TE buffer** with 200 μl of **QuantiFluor® dsDNA Dye** Working Solution in an empty **0.5 ml PCR tube**. **Vortex** well and protect tube from light (we do this by covering the tube with aluminum foil).

        -   ELP pipetted 2 micro l of 1X TE buffer into 0.5ml tube at 12:37

            4\. Prepare Standard: Add 2 μl of the provided **DNA Standard** (100 ng/μl) to 200 μl of **QuantiFluor® dsDNA Dye** working solution in an empty **0.5 ml PCR tube**. **Vortex** well and protect tube from light.

        -   ELP pipetted 2 microl l of DNA Standard into 0.5 tube at 12:39

            5\. Prepare Samples to be quantified: Add 1 or 2 μl of unknown samples to 200 μl of **QuantiFluor® dsDNA Dye** working solution in **0.5 ml PCR tubes**. **Vortex** well, and protect tube from light. You will want to pipet the sample up and down multiple times to make sure the sample is well-blended.

        -   JRE pipetted 2 micro l from samples CL, 01, 02, 03. Completed at 12:44.

        -   ELP pipetted 2 micro l from samples 04, 05, 06, 07. Completed at 12:47.

        -   FAB pipetted 2 micro l from samples 08, 09, 10, 11. Completed at 12:50

        -   JRE vortexed each sample briefly. Completed at 12:52.

            6\. Incubate the prepared samples at room temperature for 5 minutes, protected from light.

        -   Finished incubating at 12:58.

            7\. Select the dsDNA protocol on the **Quantus Fluorometer**.

        -   Completed by ELP at .

            8\. Prior to running samples on the Quantus Fluorometer, you should blend them well by **vortexing** briefly and then spinning them down briefly using the **microcentrifuge**. You should also wipe down the sides of the tubes with **kimwipes** to make sure the sides are clear from smudges. 

        -   ELP vortexed and centrifuged each sample 2 at a time while JRE placed in Quantus.

            9\. If needed (you will need it!), calibrate the **Quantus Fluorometer** by reading the blank (Step 3; this should read as 0 ng/μl) and standard (Step 4; this should read as 100 ng/μl) samples in the Calibration screen, then select "Save". 

            -   **Note**: a few ng/μl away from what it should be is ok... but large deviations need to be troubleshooted!

        -   Calibration complete at 1:00.

            10\. Enter the volume of the unknown sample (1--2 μl used in Step 5) and desired concentration units (in our case, ng/μl).

        -   Already set prior to starting

            11\. Pipette to mix each sample at least 10 times before putting the desired amount in the working solution. 

        -   Done

            12\. One sample at a time, mix by vortexing, briefly spin down and wipe the outside of the tube with a kimwipe. Measure fluorescence of the unknown sample and record the final sample concentration results.

            BL read as: 0.08 ng/uL

            Standard read as: 100 ng/uL

    1.  Clean pedestal w kimwipes and nuclease free water
        -   ELP completed at 1:06.
    2.  Blank w 2 micro l of nuclease free water or storage medium (Buffer ATE)
        -   ELP blanked with Buffer ATE. Completed at 1:07
    3.  Between each sample, clean w kim wipe and nuclease free water
    4.  2 micro l of sample for each run

+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| Sample ID               | Taxon                | Label      | Final Concentration (ng/𝜇l) | **A260/A280 value** | Notes                                                  |
+=========================+======================+============+=============================+=====================+========================================================+
| Control (sterile water) | NA                   | AGI24-DBCL | 0.04 -Q 0.8-N               | 0.76                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| GOMEZ-18-190            | Lagothrix lagotricha | AGI24-DB01 | 8.6 - Q 4.3-N               | 1.42                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-029             | Lagothrix lagotricha | AGI24-DB02 | 1.42 - Q -4.3 -N            | 1.16                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-017             | Lagothrix lagotricha | AGI24-DB03 | 2.2 - Q 2.4 -N              | 1.35                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-036             | Lagothrix lagotricha | AGI24-DB04 | 2.62 - Q 3.9 -N             | 1.71                | Maybe not the entire 200𝜇l                             |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| GIUNCHI-18-001          | Lagothrix lagotricha | AGI24-DB05 | 8.4 - Q 6.2 -N              | 1.83                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-025          | Lagothrix lagotricha | AGI24-DB06 | 1.17 - Q 1.0 -N             | 0.19                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-026          | Lagothrix lagotricha | AGI24-DB07 | 5.2 - Q 5.6 -N              | 1.85                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-027          | Lagothrix lagotricha | AGI24-DB08 | 0.436 - Q 3.3 -N            | 1.67                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-031          | Lagothrix lagotricha | AGI24-DB09 | 1.33 -Q                     | 1.79                |                                                        |
|                         |                      |            |                             |                     |                                                        |
|                         |                      |            | 2.2-N                       |                     |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-006             | Lagothrix lagotricha | AGI24-DB10 | 7.2 -Q                      | 1.78                | Pipetted most of 200 then a tiny bit extra some chunks |
|                         |                      |            |                             |                     |                                                        |
|                         |                      |            | 9.0-N                       |                     |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-032          | Lagothrix lagotricha | AGI24-DB11 | 1.77 -Q                     | 1.40                | Slightly less buffer was added                         |
|                         |                      |            |                             |                     |                                                        |
|                         |                      |            | 2.7-N                       |                     |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+

# Mar 25 - Mar 31

## March 28, 2024 (Post AABA re-quantitating)

-   1\. If necessary, prepare **1X TE Buffer**: to do this, you may need to dilute **20X TE Buffer** 20-fold with **nuclease-free water**. We do also have 1X TE BUffer available in the cabinet above the Centrifuge Workstation; there may also be pre-prepared 1X TE Buffer in the Underbench Fridge.

-   JRE mixed 10% bleach at 4:30, ethanol water bleach wiped.

-   JRE and ELP made and aliquotted 1X TE Buffer at 4:40.

    -   2\. Prepare Working Solution: Dilute the **QuantiFluor® dsDNA Dye** 1:400 in **1X TE buffer**, and mix. Working Solution may be available in the Underbench Fridge.

        -   ELP and JRE made 1.2 ml (3 parts dye to 1,197 TEx1 three times) Working solution following protocol at 12:23.

        -   JRE vortexed working solution at 12:31.

        -   JRE added 200 micro l of working solution into 14 autoclaved 0.5 ml tubes. Completed at 5:18.

            3\. Prepare Blank sample: Mix 2 μl of **1X TE buffer** with 200 μl of **QuantiFluor® dsDNA Dye** Working Solution in an empty **0.5 ml PCR tube**. **Vortex** well and protect tube from light (we do this by covering the tube with aluminum foil).

        -   ELP pipetted 2 micro l of 1X TE buffer into 0.5ml tube at 5:10

            4\. Prepare Standard: Add 2 μl of the provided **DNA Standard** (100 ng/μl) to 200 μl of **QuantiFluor® dsDNA Dye** working solution in an empty **0.5 ml PCR tube**. **Vortex** well and protect tube from light.

        -   ELP pipetted 2 microl l of DNA Standard into 0.5 tube at 5:10

            5\. Prepare Samples to be quantified: Add 1 or 2 μl of unknown samples to 200 μl of **QuantiFluor® dsDNA Dye** working solution in **0.5 ml PCR tubes**. **Vortex** well, and protect tube from light. You will want to pipet the sample up and down multiple times to make sure the sample is well-blended.

        -   JRE pipetted 2 micro l from all samples. Completed at 5:10.

            6\. Incubate the prepared samples at room temperature for 5 minutes, protected from light.

        -   Finished incubating at 5:24.

        -   Repipetted into smaller tubes starting at 5:25, ended at 5:35.

            7\. Select the dsDNA protocol on the **Quantus Fluorometer**.

        -   Completed by JRE and ELP at 5:35.

            8\. Prior to running samples on the Quantus Fluorometer, you should blend them well by **vortexing** briefly and then spinning them down briefly using the **microcentrifuge**. You should also wipe down the sides of the tubes with **kimwipes** to make sure the sides are clear from smudges. 

        -   ELP vortexed and centrifuged each sample 2 at a time while JRE placed in Quantus.

            9\. If needed (you will need it!), calibrate the **Quantus Fluorometer** by reading the blank (Step 3; this should read as 0 ng/μl) and standard (Step 4; this should read as 100 ng/μl) samples in the Calibration screen, then select "Save". 

            -   **Note**: a few ng/μl away from what it should be is ok... but large deviations need to be troubleshooted!

        -   Calibration complete at 5:36.

            10\. Enter the volume of the unknown sample (1--2 μl used in Step 5) and desired concentration units (in our case, ng/μl).

        -   Already set prior to starting

            11\. Pipette to mix each sample at least 10 times before putting the desired amount in the working solution. 

        -   Done

            12\. One sample at a time, mix by vortexing, briefly spin down and wipe the outside of the tube with a kimwipe. Measure fluorescence of the unknown sample and record the final sample concentration results.

            BL read as: Lower than contol

            Standard read as: 100 ng/uL

    1.  Clean pedestal w kimwipes and nuclease free water
        -   ELP completed at 1:06.
    2.  Blank w 2 micro l of nuclease free water or storage medium (Buffer ATE)
        -   ELP blanked with Buffer ATE. Completed at 1:07
    3.  Between each sample, clean w kim wipe and nuclease free water
    4.  2 micro l of sample for each run

REDOING original quantitation!

+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| Sample ID               | Taxon                | Label      | Final Concentration (ng/𝜇l) | **A260/A280 value** | Notes                                                  |
+=========================+======================+============+=============================+=====================+========================================================+
| Control (sterile water) | NA                   | AGI24-DBCL | 0.686 -Q 0.8-N              | 0.76                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| GOMEZ-18-190            | Lagothrix lagotricha | AGI24-DB01 | 0.0012 - Q 4.3-N            | 1.42                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-029             | Lagothrix lagotricha | AGI24-DB02 | 0.921 - Q -4.3 -N           | 1.16                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-017             | Lagothrix lagotricha | AGI24-DB03 | 0.354 - Q 2.4 -N            | 1.35                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-036             | Lagothrix lagotricha | AGI24-DB04 | 0.860 - Q 3.9 -N            | 1.71                | Maybe not the entire 200𝜇l                             |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| GIUNCHI-18-001          | Lagothrix lagotricha | AGI24-DB05 | 1.79 - Q 6.2 -N             | 1.83                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-025          | Lagothrix lagotricha | AGI24-DB06 | 0.711 - Q 1.0 -N            | 0.19                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-026          | Lagothrix lagotricha | AGI24-DB07 | 3.19 - Q 5.6 -N             | 1.85                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-027          | Lagothrix lagotricha | AGI24-DB08 | 0.354 - Q 3.3 -N            | 1.67                |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-031          | Lagothrix lagotricha | AGI24-DB09 | 0.292 -Q                    | 1.79                |                                                        |
|                         |                      |            |                             |                     |                                                        |
|                         |                      |            | 2.2-N                       |                     |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| VOYT-18-006             | Lagothrix lagotricha | AGI24-DB10 | 5.2 -Q                      | 1.78                | Pipetted most of 200 then a tiny bit extra some chunks |
|                         |                      |            |                             |                     |                                                        |
|                         |                      |            | 9.0-N                       |                     |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+
| DIFIORE-18-032          | Lagothrix lagotricha | AGI24-DB11 | 0.821 -Q                    | 1.40                | Slightly less buffer was added                         |
|                         |                      |            |                             |                     |                                                        |
|                         |                      |            | 2.7-N                       |                     |                                                        |
+-------------------------+----------------------+------------+-----------------------------+---------------------+--------------------------------------------------------+

#  
